name: Check TODOs in Codebase

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.2"
