name: Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - "*"

jobs:
  Cancel-previous-jobs:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4.7.3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_PYTHON_BLACK: true

  Linting:
    runs-on: ubuntu-latest
    env:
      GISAID_API_TOKEN: ${{ secrets.GISAID_API_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"

# TODO: Search for Testdata and activate GitHub Actions testing
  # Testing:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - Formatting
  #     - Linting
      # env:
      #   GISAID_API_TOKEN: ${{ secrets.GISAID_API_TOKEN }}
  #   steps:

  #     - uses: actions/checkout@v2

  #     - name: Checkout submodules
  #       uses: textbook/git-checkout-submodule-action@2.0.0

  #     - name: Test workflow (local test data)
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .tests
  #         snakefile: workflow/Snakefile
  #         args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs"

  #     - name: Test report
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .test
  #         snakefile: workflow/Snakefile
  #         args: "--report report.zip"
